# Generated by Django 5.1.1 on 2024-10-07 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('car_plate', models.CharField(max_length=255)),
                ('mileage', models.FloatField()),
                ('engine_size', models.FloatField()),
                ('fuel', models.CharField(max_length=255)),
                ('gearbox', models.CharField(max_length=255)),
                ('air_contidion', models.BooleanField()),
                ('number_of_seats', models.IntegerField()),
                ('number_of_doors', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('body_style', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
            ],
            options={
                'verbose_name': 'Car For Rental',
                'verbose_name_plural': 'Cars For Rental',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
                'ordering': ['-timestamp'],
            },
        ),
    ]
