# Generated by Django 5.0.6 on 2024-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalApp", "0002_cars_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="category",
            field=models.CharField(max_length=255),
        ),
    ]
